### ISSUE TITLE
Can I borrow your code to create lib for noise effect?

### ISSUE THREAD

**Issue by hypeapps** [danielzeller/Depth-LIB-Android-#21]
I would cut of part of your lib responsible for noise effect, rewrite it to kotlin, add some features and finally host on my github on MIT license. I will post info in readme that code is based on your library. What do you think? Can I do something like that?

**Comment by danielzeller** [comment]
Sure have fun with it, that's why it's up on GitHub! Send me the link once your'e done so I can check it out :)

**Comment by hypeapps** [comment]
@danielzeller Done :) [https://github.com/hypeapps/NoiseView](https://github.com/hypeapps/NoiseView)
