### ISSUE TITLE
Not yours Lib

### ISSUE THREAD

**Issue by yuger** [danielzeller/Depth-LIB-Android-#3]
You are just copied from https://github.com/yongjhih/depth ,it's not a good way...

**Comment by danielzeller** [comment]
Hate to tell you this but this is the original project! The other one must have been reverse engineered from the Google play app or something! That is not cool! Note the lib is made by Agens AS https://www.agens.no/the-company/ and I am a developer there!

**Comment by danielzeller** [comment]
Thanks for pointing that out for me! I will have him remove his stolen code... So not cool!

**Comment by danielzeller** [comment]
The other stolen LIB has been removed.

**Comment by yuger** [comment]
Oh, I get it ,thanks

**Comment by yongjhih** [comment]
See also: https://github.com/yongjhih/depth/issues/1

Before, README has already represented obviously that imported from no.agens.depth.apk and author is twitter/@zellah, I didn't expect somebody confused, I'm sorry.
